### ISSUE TITLE
Feature request: Uncollapse all classes

### ISSUE THREAD

**Issue by pm64** [theron-wang/Class-Hide#1]
This is an extremely useful extension. Would you consider implementing "Uncollapse all classes"?

The keyboard shortcut (Ctrl+R, Ctrl+H) could serve as a toggle to collapse/uncollapse.

The option in the Tools menu could vary -- either "Collapse all classes" or "Uncollapse all classes", depending on whether any classes are currently collapsed.

If some (but not all) classes are currently collapsed, the toggling action would be to collapse the remainder of the classes.

**Comment by theron-wang** [comment]
Of course, added in 1.1.0. However, I chose not to make the text in the Tools menu dynamic (always Collapse/Uncollapse All Classes), since doing so may be a somewhat expensive task (mostly in larger files). Thank you!

**Comment by pm64** [comment]
Works perfectly @theron-wang. Sincerest thanks for fulfilling this request.
