### ISSUE TITLE
Can we make it not highlight lines with collapsed class attributes?

### ISSUE THREAD

**Issue by skttl** [theron-wang/Class-Hide#3]
When the extension collapses class attributes, it makes Visual Studio somehow highlight the lines containing collapsed class attributes.

Is there any way we can prevent this (without changing the highlighting when you use the built in collapse functionality for collapsing elements)? To me it makes it more confusing :)

![image](https://github.com/user-attachments/assets/9ad2b711-1400-4b20-86d5-ec8b240444cf)

**Comment by theron-wang** [comment]
Unfortunately, this is not something the extension can control. If you don't want these to be highlighted, you can change this in your settings in Tools > Options > Environment > Fonts and Colors > Collapsible Region, then click 'Custom' for Item Background.

![image](https://github.com/user-attachments/assets/8fb52b37-2d49-4e6a-a22e-4e4c060e06fe)

Assuming you are using the default VS dark mode theme, the correct background color should be rgb(30, 30, 30). I hope this helps!
